//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dookki_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminID { get; set; }
        public string adminUserName { get; set; }
        public string adminPassword { get; set; }
        public string adminPhone { get; set; }
        public string adminName { get; set; }
        public string roles { get; set; }
    }
}
