//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dookki_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayWork
    {
        public int dayWorkId { get; set; }
        public Nullable<int> timeWork { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<int> employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
