//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dookki_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DayWorks = new HashSet<DayWork>();
        }
    
        public int employeeID { get; set; }
        public string employeeName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public decimal amountWage { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<DayWork> DayWorks { get; set; }
    }
}
