//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dookki_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        public Ticket()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Tên vé không được để trống.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Giá vé là bắt buộc")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá vé phải là một số dương")]
        public decimal Price { get; set; }


        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
